kind: pipeline
type: docker
name: building

steps:
  - name: compile
    image: node:20.11.0
    commands:
      - npm config set registry https://registry.kernotec.com/repository/npm-central/
      - npm config set //registry.kernotec.com/repository/npm-central/:_auth=Z2l0aHViOnRST0NBVkxQcmVzcDVmaVBoZXBy
      - npm install -g @angular/cli
      - npm install npm@latest
      - cp src/environments/environment.prod.ts src/environments/environment.ts
      - npm install
      - ng build --configuration=production
    when:
      repo:
        - KernoTec/${DRONE_REPO_NAME}
      event:
        - push
        - pull_request
        - tag

  - name: docker-pr
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile
      registry: hub.kernotec.com
      repo: hub.kernotec.com/kernotec/kbi-tesoreria-ui
      tags: ${DRONE_PULL_REQUEST}
      username:
        from_secret: kernotec_username
      password:
        from_secret: kernotec_password
    when:
      repo:
        - KernoTec/${DRONE_REPO_NAME}
      event:
        - pull_request

  - name: docker-push-env
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile
      registry: hub.kernotec.com
      repo: hub.kernotec.com/kernotec/kbi-tesoreria-ui
      tags: ${DRONE_BRANCH/\//_}
      username:
        from_secret: kernotec_username
      password:
        from_secret: kernotec_password
    when:
      branch:
        - develop
        - sandbox
      repo:
        - KernoTec/${DRONE_REPO_NAME}
      event:
        - push

  - name: docker-push-latest
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile
      registry: hub.kernotec.com
      repo: hub.kernotec.com/kernotec/kbi-tesoreria-ui
      tags: latest
      username:
        from_secret: kernotec_username
      password:
        from_secret: kernotec_password
    when:
      branch:
        - main
      repo:
        - KernoTec/${DRONE_REPO_NAME}
      event:
        - push
